packages:
  - packages/**
  - scripts

allowBuilds:
  esbuild: true

catalog:
  '@biomejs/biome': ^2.4.7
  '@lexical/code': ^0.41.0
  '@lexical/link': ^0.41.0
  '@lexical/list': ^0.41.0
  '@lexical/markdown': ^0.41.0
  '@lexical/react': ^0.41.0
  '@lexical/rich-text': ^0.41.0
  '@std/front-matter': jsr:^1.0.9
  '@std/yaml': jsr:^1.0.12
  '@tailwindcss/vite': ^4.2.2
  '@types/node': ^25.5.0
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  '@typescript/native-preview': 7.0.0-dev.20260317.1
  '@vitejs/plugin-react': ^6.0.1
  lexical: ^0.41.0
  react: ^19.2.4
  react-dom: ^19.2.4

  repojj: ^2026.1.35
  tailwindcss: ^4.2.2
  typescript: ^5.9.3
  vite: ^8.0.1
  vitest: ~4.1.0
  zod: ^4.3.6

catalogMode: strict

cleanupUnusedCatalogs: true
